api = "0.8"

[buildpack]
  id = "knecon/tessdata"
  name = "vcpkg cmake buildpack"
  description = "Downloads tessdata from tesseract_languages file and sets the TESSDATA_PREFIX environment variable"
  version = "0.1.0"
  keywords = ["tessdata", "tesseract", "leptonica"]

[[stacks]]
  id = "io.buildpacks.stacks.jammy"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[targets]]
  os = "linux"

[[requires]]
  name = "curl"
